# Generated by Django 4.0.6 on 2022-09-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
