# Generated by Django 4.0.6 on 2022-09-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_alter_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
