# Generated by Django 4.0.6 on 2022-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Чоловік', 'Чоловік'), ('F', 'Жінка')], default='Чоловік', max_length=10),
        ),
    ]
