# Generated by Django 4.0.6 on 2022-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('MA', 'Чоловік'), ('FE', 'Жінка')], default='MA', max_length=2),
        ),
    ]
