# Generated by Django 4.0.6 on 2022-09-13 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0023_alter_actor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
