# Generated by Django 4.0.6 on 2022-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0024_movie_viewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeresidence',
            name='map_coordinate',
            field=models.URLField(default='https://www.google.com/maps'),
        ),
    ]
