# Generated by Django 4.0.6 on 2022-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0027_alter_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_imdb',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
