# Generated by Django 4.0.6 on 2022-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0031_movie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/my_gallery', verbose_name='Image'),
        ),
    ]
