# Generated by Django 4.0.6 on 2022-09-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0034_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
