# Generated by Django 4.0.6 on 2022-09-16 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0035_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='viewed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
