# Generated by Django 4.0.6 on 2022-09-27 10:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0036_alter_movie_viewed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='my_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='viewed_date',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адреса')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('viewed_date', models.DateField(default=datetime.date.today)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie', verbose_name='Фільм')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='')),
                ('surname', models.CharField(max_length=60, verbose_name='')),
                ('feedback', models.TextField(max_length=5000, verbose_name='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie', verbose_name='Фільм')),
            ],
        ),
    ]
