# Generated by Django 4.0.6 on 2022-09-28 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0039_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Ч', 'Чоловік'), ('Ж', 'Жінка')], default='Ч', max_length=10, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.placeresidence', verbose_name='Місце проживання'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movie_app.actor', verbose_name='Актори'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_app.director', verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movie_app.genre', verbose_name='Жанри'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_name',
            field=models.CharField(max_length=50, verbose_name='Англійською'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='my_gallery', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_imdb',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2100)], verbose_name='Рік'),
        ),
        migrations.AlterField(
            model_name='placeresidence',
            name='city',
            field=models.CharField(max_length=40, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='placeresidence',
            name='country',
            field=models.CharField(max_length=40, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='placeresidence',
            name='map_coordinate',
            field=models.URLField(default='https://www.google.com/maps', verbose_name='Координати на мапі'),
        ),
        migrations.AlterField(
            model_name='placeresidence',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='placeresidence',
            name='street',
            field=models.CharField(max_length=40, verbose_name='Вулиця'),
        ),
    ]
