# Generated by Django 4.0.6 on 2022-09-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0040_alter_actor_first_name_alter_actor_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
    ]
