# Generated by Django 4.0.6 on 2022-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0043_alter_rating_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=20, verbose_name="Ім'я"),
        ),
    ]
