# Generated by Django 4.0.6 on 2022-11-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0045_remove_feedback_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актор', 'verbose_name_plural': 'Актори'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режисер', 'verbose_name_plural': 'Режисери'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterModelOptions(
            name='placeresidence',
            options={'verbose_name': 'Місце проживання', 'verbose_name_plural': 'Місця проживання'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_rating', to='movie_app.movie', verbose_name='Фільм'),
        ),
    ]
